site_name: halc
theme:
    name: "material"
plugins:
  - markdownmermaid
  - search
  - mkdocstrings:
      watch:
        - halc
extra_javascript:
    - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js